### PR TITLE
Fix issue #64, make badges clickable

### PR DESCRIPTION
**Pull request by schalkneethling**
@FrancescoSTL r? The covers:

* https://github.com/mozilla/all-aboard/issues/64
* https://github.com/mozilla/all-aboard/issues/179

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
A couple of things:
1. Badges aren't clickable until the interaction happens. Was that intentional?
2. I don't know currently assigned tokens should be clickable. IE, clicking a token for a sidebar that is currently open which reloads the sidebar. This does allow users to go back and answer the question multiple times to see what the responses are, however, it might be bad UX to have the sidebar load again. Thoughts? @schalkneethling @chrismore

**Comment by schalkneethling** [comment]
> 1. Badges aren't clickable until the interaction happens. Was that intentional?
You should only be able to click on badges that has been awarded. You mean you can only click on awarded badges after you completed the initial CTA?

> 2.  I don't know currently assigned tokens should be clickable.
Fair point. I think it is unlikely that a user will click on the token they just received but, and if they do, it is hardly noticeable(if at all) the the sidebar reloads.

If @chrismore or yourself feel strongly to the contrary, then I can change it so this does not happen but, perhaps we can merge this and handle it afterwards, there is a lot of win in merging this PR :) Just a thought. Thanks!

**Comment by FrancescoSTL** [comment]
@schalkneethling My sidebar doesn't seem to be auto closing anymore after interaction or after opening

**Comment by schalkneethling** [comment]
Just checked, and you can immediately interact with awarded badges, just not those you have not received, which is what we want.

**Comment by schalkneethling** [comment]
> My sidebar doesn't seem to be auto closing anymore after interaction or after opening

If you clicked on any of the tokens, all auto closing for the current sidebar is disabled until you close, and reopen it or, cycle to the next sidebar in the track.

**Comment by FrancescoSTL** [comment]
> If you clicked on any of the tokens, all auto closing for the current sidebar is disabled until you close, and reopen it or, cycle to the next sidebar in the track.

@schalkneethling ah, I see. That may be my issue. Let me check again.

**Comment by chrismore** [comment]
@schalkneethling @FrancescoSTL I am good with everything above.

**Comment by schalkneethling** [comment]
Just checked and confirmed as mentioned in https://github.com/mozilla/all-aboard/pull/218#issuecomment-229986847

**Comment by FrancescoSTL** [comment]
@schalkneethling One last thing, the ActionButton icon shows up when navigating away from the firstrun page. Per conversation with @chrismore, we should only show that button when the user is first given a sidebar, as if we leave the icon there, they can access the first sidebar immediately after leaving firstrun

**Comment by FrancescoSTL** [comment]
@chrismore If this is not a big deal we can merge now and fix later, being that we are on a tight schedule. ^

**Comment by schalkneethling** [comment]
> One last thing, the ActionButton icon shows up when navigating away from the firstrun page.

The `ActionButton` needs to be there before the first notification or else the add-on will throw and error as `allAboard` is undefined. There is another bug I have discovered in this regard, but it is not introduced here so, I will fix it in a follow on PR.

**Comment by FrancescoSTL** [comment]
@schalkneethling In that case, I'll merge this now and we can fix later. r+ 🐺

**Comment by chrismore** [comment]
As discussed on IRC, I like the idea if users can get started early.

**Comment by chrismore** [comment]
The notification is just there for users who get overwhelmed easily

**Pull request merged**
