### PR TITLE
Fix issue #133, add intro copy to firstrun questions

### PR DESCRIPTION
**Pull request by schalkneethling**
@chrismore r?

Here is how the layout looks. With some of the layout changes, I was not exactly sure where we wanted the copy added, so I took a stab at it.

intro_copy 15 33 15

### CODE REVIEW

**Comment by chrismore** [comment]
@schalkneethling as showed in issue #133, add the "help us" sentence to the bottom of the main or footer in the gray instead of the white header. It should be in the grey at the bottom and should be displayed regardless if one or two questions are displayed.

**Comment by schalkneethling** [comment]
@chrismore Ah ok, as we were hiding the entire footer with the button, I  was thinking that perhaps we wanted to place the string somewhere else. I will update accordingly.

**Comment by schalkneethling** [comment]
@chrismore updated

**Comment by chrismore** [comment]
@schalkneethling almost there. Can you make the text not centered in the div and text-align left. Also, make the font-size: .75rem. I am trying to make it so that when the blue button appears, it doesn't shift the text and make it wrap. I just want the blue button to appear after you answer the second question. Let me know when you have it updated and I'll check it again. Thanks!

**Comment by chrismore** [comment]
screen shot 2016-06-26 at 10 50 23 pm

**Comment by chrismore** [comment]
Oh, and add a period at the end of the sentence.

**Comment by schalkneethling** [comment]
@chrismore updated

**Comment by FrancescoSTL** [comment]
Can review after #175 is fixed

**Comment by FrancescoSTL** [comment]
@schalkneethling this one needs a rebase

**Comment by schalkneethling** [comment]
@FrancescoSTL rebased

**Comment by FrancescoSTL** [comment]
@schalkneethling currently getting `dialog is undefined` at `resource://all-aboard/data/js/firstrun.js:51:5`, and there is no form showing on the page.

**Comment by FrancescoSTL** [comment]
screen shot 2016-06-27 at 10 16 51 am

**Comment by schalkneethling** [comment]
@FrancescoSTL hmmm, reckon something went wrong with the merge, will have a look

**Comment by schalkneethling** [comment]
@FrancescoSTL resolved.

**Comment by FrancescoSTL** [comment]
Lookin pretty good. r+ 🌈

**Pull request merged**
