### PR TITLE
Fix issue#323, TG-146 #closed, auto open sidebar on first notification

### PR DESCRIPTION
**Pull request by schalkneethling**
@FrancescoSTL @chrismore This is still WIP but, wanted to open it up so you can see where I am at. It works, but I need to do some additional testing to be sure. I also need to actually implement the enhancement :)

We can talk more in the standup but, I reckon we can safely shoot for Monday EOmyD to have this ready for official review and merging.

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
Just a heads up (not sure if this is known), but it seems that the auto-import stuff on new-tab is showing all the time. I'm not certain if that is a result of AutoImport being uplifted through the trains or a regression existing.
screen shot 2016-08-12 at 10 13 07 am

**Comment by FrancescoSTL** [comment]
PS: Great work on modularizing this. It looks much more maintainable now that we've got everything split into separate files. Once we begin working with WebExtensions in v2 (or whenever that might be) we can use [Browserify](http://browserify.org/) to maintain modularity. Although it doesn't include all the functionality of CommonJS, its better than having one large index.js file again :).

**Comment by schalkneethling** [comment]
@FrancescoSTL against which build are you running? I do not have one that actually has auto import i.e. AutoMigrate so, I am just getting the error "Unable to access automigrate.jsm"

**Comment by FrancescoSTL** [comment]
@schalkneethling Running against Developer Edition. Sounds like AutoImport has been riding the trains for long enough to reach Aurora then :)

**Comment by schalkneethling** [comment]
Alrighty. @FrancescoSTL this is ready for review and testing.

**Comment by FrancescoSTL** [comment]
Looks good. I sincerely attempted to break this, but I couldn't find any issues :).

Great work @schalkneethling!

**Pull request merged**
