### PR TITLE
Fix issue #85, toggle existing sidebar when icon clicked

### PR DESCRIPTION
**Pull request by schalkneethling**
@chrismore r? I believe this also fixes https://github.com/mozilla/all-aboard/issues/132

### CODE REVIEW

**Comment by chrismore** [comment]
@schalkneethling I just tested this PR and it doesn't fix #132. If I close a sidebar without interacting with it, clicking the light bulb will not open it.

**Comment by schalkneethling** [comment]
@chrismore that is super weird, I tested that and it seemed to work. Let me look at it again.

**Comment by schalkneethling** [comment]
This is what I am seeing:
values

**Comment by schalkneethling** [comment]
@chrismore Have you tested this again? It definitely works for me as shown above. I have also just tested it again and I cannot reproduce the issue you describe in https://github.com/mozilla/all-aboard/pull/167#issuecomment-228145534

**Comment by schalkneethling** [comment]
@chrismore I am going to merge this, simply because I want to tackle https://github.com/mozilla/all-aboard/issues/137, and it kinda depends on this. If you still find that it does not work after it is merged to master, please let me know and I will investigate further. Thanks!

**Pull request merged**
