### PR TITLE
Fix issue #166, adds heres you badge to all tracks

### PR DESCRIPTION
**Pull request by schalkneethling**
@FrancescoSTL r?

### CODE REVIEW

**Comment by FrancescoSTL** [comment]
@schalkneethling If a user receives a badge, closes the sidebar, reopens, and performs the task again, they will be given the "Here's your badge!" message. On the values side, maybe we prefill the answered values when the sidebar is reopened? On the utility side, however, I don't think the user should be prompted again with the "here's your badge" message twice.

**Comment by schalkneethling** [comment]
@FrancescoSTL Yeah, I was thinking the same thing. I reckon I will pass a value to the sidebar to indicate whether the token has been assigned already or not. I remember we discussed the idea of keeping state for some of the sidebars, especially values track, but decided not to.

So I reckon, the first time we show the message, and on following interactions we just not show it at all as the badge is already there.

**Comment by FrancescoSTL** [comment]
@schalkneethling sounds good to me +1

**Comment by chrismore** [comment]
@schalkneethling ^^

**Comment by chrismore** [comment]
Just a quick note about the .625rem for the here's your badge copy

**Comment by chrismore** [comment]
@schalkneethling I'm heavily leaning toward moving the "Here's your badge" below the tokens. Why? Because we are at the max size now for the smallest resolution and I am thinking I would rather have people see the badges than text that says "Here's your badge" and then having it push the token. So same everything, but "Here's your badge" below the tokens. If the copy doesn't show up for small resolutions, it is not the end of the world.

**Comment by schalkneethling** [comment]
@FrancescoSTL @chrismore updated and ready for review.

**Comment by FrancescoSTL** [comment]
r+ 🌈

**Pull request merged**
