### PR TITLE
Adds functional test for flow from firstrun to second sidebar notification

### PR DESCRIPTION
**Pull request by schalkneethling**
@FrancescoSTL r?

### CODE REVIEW

**Comment by schalkneethling** [comment]
to run the tests you would do:

```
workon all-aboard # or whatever you called the virtualenv
cd tests-functional
tox -e tests -- --firefox-path=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox
```

**Comment by FrancescoSTL** [comment]
So I've been attempting to get the functional tests running on and off today to test out this PR. Turns out its proving to be harder than expected. I was unable to get the geckodriver to install via the executable I downloaded on github, so I tried grabbing it from brew. I got the functional tests to start (I believe), however, it seems that they fail after a while. Here is the long tail:

```
(all-aboard)Francescos-MBP:tests-functional fpolizzi$ tox -e tests -- --firefox-path=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox
tests installed: PyPOM==1.0,apipkg==1.4,argparse==1.3.0,execnet==1.4.1,pbr==0.11.0,py==1.4.31,pytest==2.9.2,pytest-base-url==1.1.0,pytest-html==1.10.0,pytest-selenium==1.3.1,pytest-variables==1.4,pytest-xdist==1.14,requests==2.11.1,selenium==2.53.6,six==1.9.0,stevedore==1.4.0,virtualenv==12.1.1,virtualenv-clone==0.2.5,virtualenvwrapper==4.3.1,wsgiref==0.1.2
tests runtests: PYTHONHASHSEED='2919650604'
tests runtests: commands[0] | py.test --firefox-path=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox
============================================================================================================================ test session starts ============================================================================================================================
platform darwin -- Python 2.7.9, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/python2.7
cachedir: .cache
baseurl: https://www.mozilla.org
sensitiveurl: None
driver: Firefox
rootdir: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional, inifile: setup.cfg
plugins: base-url-1.1.0, html-1.10.0, selenium-1.3.1, variables-1.4, xdist-1.14
[gw0] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw1] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw2] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw3] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw4] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw5] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw6] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw7] darwin Python 2.7.9 cwd: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional
[gw0] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw5] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw4] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw1] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw2] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw3] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw6] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
[gw7] Python 2.7.9 (default, May 22 2015, 13:29:23)  -- [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
gw0 [4] / gw1 [4] / gw2 [4] / gw3 [4] / gw4 [4] / gw5 [4] / gw6 [4] / gw7 [4]
scheduling tests via LoadScheduling

tests/test_firstrun.py::test_firstrun_allaboard_dialog_interaction 
tests/test_all_aboard_values.py::test_first_sidebar_loads 
tests/test_firstrun.py::test_dismiss_onboarding 
tests/test_firstrun.py::test_open_firstrun_page 
[gw7] ERROR tests/test_firstrun.py::test_firstrun_allaboard_dialog_interaction 
[gw6] ERROR tests/test_firstrun.py::test_dismiss_onboarding 
[gw1] ERROR tests/test_firstrun.py::test_open_firstrun_page 
[gw5] ERROR tests/test_all_aboard_values.py::test_first_sidebar_loads 

---------------------------------------------------------------------------------- generated xml file: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/results/junit.xml ----------------------------------------------------------------------------------
--------------------------------------------------------------------------------- generated html file: /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/results/index.html ---------------------------------------------------------------------------------
========================================================================================================================== short test summary info ==========================================================================================================================
ERROR tests/test_firstrun.py::test_firstrun_allaboard_dialog_interaction
ERROR tests/test_firstrun.py::test_dismiss_onboarding
ERROR tests/test_firstrun.py::test_open_firstrun_page
ERROR tests/test_all_aboard_values.py::test_first_sidebar_loads
================================================================================================================================== ERRORS ===================================================================================================================================
_______________________________________________________________________________________________________ ERROR at setup of test_firstrun_allaboard_dialog_interaction ________________________________________________________________________________________________________
[gw7] darwin -- Python 2.7.9 /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/python2.7
request = <SubRequest 'selenium' for <Function 'test_firstrun_allaboard_dialog_interaction'>>

    @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

.tox/tests/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/tests/lib/python2.7/site-packages/pytest_selenium/drivers/firefox.py:46: in firefox_driver
    return Firefox(**kwargs)
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:65: in __init__
    self.service.start()
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:86: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.firefox.service.Service object at 0x101940090>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
            raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
>               % (self.path, return_code)
            )
E           WebDriverException: Message: Service wires unexpectedly exited. Status code was: 1

.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:99: WebDriverException
_________________________________________________________________________________________________________________ ERROR at setup of test_dismiss_onboarding _________________________________________________________________________________________________________________
[gw6] darwin -- Python 2.7.9 /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/python2.7
request = <SubRequest 'selenium' for <Function 'test_dismiss_onboarding'>>

    @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

.tox/tests/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/tests/lib/python2.7/site-packages/pytest_selenium/drivers/firefox.py:46: in firefox_driver
    return Firefox(**kwargs)
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:65: in __init__
    self.service.start()
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:86: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.firefox.service.Service object at 0x10317d090>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
            raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
>               % (self.path, return_code)
            )
E           WebDriverException: Message: Service wires unexpectedly exited. Status code was: 1

.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:99: WebDriverException
_________________________________________________________________________________________________________________ ERROR at setup of test_open_firstrun_page _________________________________________________________________________________________________________________
[gw1] darwin -- Python 2.7.9 /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/python2.7
request = <SubRequest 'selenium' for <Function 'test_open_firstrun_page'>>

    @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

.tox/tests/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/tests/lib/python2.7/site-packages/pytest_selenium/drivers/firefox.py:46: in firefox_driver
    return Firefox(**kwargs)
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:65: in __init__
    self.service.start()
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:86: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.firefox.service.Service object at 0x10ecd6090>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
            raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
>               % (self.path, return_code)
            )
E           WebDriverException: Message: Service wires unexpectedly exited. Status code was: 1

.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:99: WebDriverException
________________________________________________________________________________________________________________ ERROR at setup of test_first_sidebar_loads _________________________________________________________________________________________________________________
[gw5] darwin -- Python 2.7.9 /Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/python2.7
request = <SubRequest 'selenium' for <Function 'test_first_sidebar_loads'>>

    @pytest.fixture
    def selenium(request):
        """Returns a WebDriver instance based on options and capabilities"""
        driver_type = request.config.getoption('driver')
        if driver_type is None:
            raise pytest.UsageError('--driver must be specified')
    
        driver_fixture = '{0}_driver'.format(driver_type.lower())
>       driver = request.getfuncargvalue(driver_fixture)

.tox/tests/lib/python2.7/site-packages/pytest_selenium/pytest_selenium.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/tests/lib/python2.7/site-packages/pytest_selenium/drivers/firefox.py:46: in firefox_driver
    return Firefox(**kwargs)
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:65: in __init__
    self.service.start()
.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:86: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.firefox.service.Service object at 0x104342110>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
            raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
>               % (self.path, return_code)
            )
E           WebDriverException: Message: Service wires unexpectedly exited. Status code was: 1

.tox/tests/lib/python2.7/site-packages/selenium/webdriver/common/service.py:99: WebDriverException
========================================================================================================================== 4 error in 2.69 seconds ==========================================================================================================================
ERROR: InvocationError: '/Users/fpozlizzi/all-aboard-mozilla/all-aboard-1/tests-functional/.tox/tests/bin/py.test --firefox-path=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox'
__________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________
ERROR:   tests: commands failed

```

**Comment by schalkneethling** [comment]
@FrancescoSTL it may be that you are using the latest gecko driver (0.10.0) and this needs to be used with a beta release of selenium 3 or thing will break. Have a go at it with version 0.9.0 [https://github.com/mozilla/geckodriver/releases/tag/v0.9.0] and see if that solves your problem.

**Comment by schalkneethling** [comment]
@FrancescoSTL any luck using the driver I mentioned above? Remember also that you need to rename the driver to `wires`

**Comment by schalkneethling** [comment]
Seeing that I am kinda blocked on moving forward with the functional tests specifically until this PR is merged, combined with the fact that I am 100% sure the tests work and that the trouble @FrancescoSTL is running into is driver related, I am going to go ahead and merge this.

**Pull request merged**
