### PR TITLE
Issue #98 - Add adjust links to mobile buttons

### PR DESCRIPTION
**Pull request by FrancescoSTL**
Issue ref: #98 

r? @chrismore

### CODE REVIEW

**Comment by chrismore** [comment]
@FrancescoSTL those just look like bit.ly links and not adjust SDK links.

I think @bniolet1 said he can make us adjust links.

**Comment by FrancescoSTL** [comment]
Ah, I thought those were the links. I'll update once we get the links from @bniolet1

**Comment by bniolet1** [comment]
Those are shortened adjust links. I can unshorten if you'd prefer: 

Android
https://app.adjust.com/2uo1qc?campaign=inprod&adgroup=fdr_addon&creative=utilityandroid


iOS
https://app.adjust.com/2uo1qc?campaign=inprod&adgroup=fdr_addon&creative=utilityios&fallback=https%3A%2F%2Fitunes.apple.com%2Fapp%2Fapple-store%2Fid989804926%3Fpt%3D373246%26ct%3Dadjust_tracker%26mt%3D8

**Comment by FrancescoSTL** [comment]
@chrismore Are we wanting the above links or the bitly style shortened ones?

**Comment by chrismore** [comment]
Ahh ok, perfect. I just wanted to make sure behind the bit.ly short links were the adjust URLs. 

@FrancescoSTL r+

**Pull request merged**
